name: "R 1.4 - Conteúdo"
description: "requisito  1.4, checklist Conteúdo"
title: "R 1.4 - Conteúdo"
labels:
  - chk conteúdo
  - R 1.4

body:
  - type: markdown
    attributes:
      value: |
        A informação sobre a entidade responsável pelo conteúdo está em todas as páginas.  
        – [ver requisito 1.4 na lista Conteúdo](https://amagovpt.github.io/kit-selo/checklists/checklist-conteudo#n14)

  - type: textarea
    id: evidencias
    attributes:
      label: Evidências
      description: Indica as evidências encontradas
      placeholder: Descreve aqui as evidências...
    validations:
      required: false

  - type: textarea
    id: recomendacoes
    attributes:
      label: Recomendações
      description: Sugere melhorias ou correções
      placeholder: Descreve aqui as recomendações...
    validations:
      required: false
