name: "R 1.2 - Transação"
description: "requisito  1.2, checklist Transação"
title: "R 1.2 - Transação"
labels:
  - chk transação
  - R 1.2

body:
  - type: markdown
    attributes:
      value: |
        Os formulários com mais de 2 ecrãs de altura devem ser distribuídos por várias páginas.  
        – [ver requisito 1.2 na lista Transação](https://amagovpt.github.io/kit-selo/checklists/checklist-transacao#n12)

  - type: textarea
    id: evidencias
    attributes:
      label: Evidências
      description: Indica as evidências encontradas
      placeholder: Descreve aqui as evidências...
    validations:
      required: false

  - type: textarea
    id: recomendacoes
    attributes:
      label: Recomendações
      description: Sugere melhorias ou correções
      placeholder: Descreve aqui as recomendações...
    validations:
      required: false
