name: "R 4.2 - Transação"
description: "requisito  4.2, checklist Transação"
title: "R 4.2 - Transação"
labels:
  - chk transação
  - R 4.2

body:
  - type: markdown
    attributes:
      value: |
        As ações destrutivas nunca devem ser permanentes, deve ser sempre possível desfazer a operação.  
        – [ver requisito 4.2 na lista Transação](https://amagovpt.github.io/kit-selo/checklists/checklist-transacao#n42)

  - type: textarea
    id: evidencias
    attributes:
      label: Evidências
      description: Indica as evidências encontradas
      placeholder: Descreve aqui as evidências...
    validations:
      required: false

  - type: textarea
    id: recomendacoes
    attributes:
      label: Recomendações
      description: Sugere melhorias ou correções
      placeholder: Descreve aqui as recomendações...
    validations:
      required: false
